// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Pastillo D Joan",
            "url": "https://www.utn.edu.ec",
            "email": "jfpastillod@utn.edu.ec"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/audit": {
            "post": {
                "description": "Registra un evento de auditoría en el sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auditoría"
                ],
                "summary": "Registrar auditoría",
                "parameters": [
                    {
                        "description": "Datos de auditoría a registrar",
                        "name": "auditData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.RegisterAuditInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Auditoría registrada exitosamente",
                        "schema": {
                            "$ref": "#/definitions/controllers.RegisterAuditResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos o formato incorrecto",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseAudit"
                        }
                    },
                    "500": {
                        "description": "Error al registrar la auditoría",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseAudit"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Autentica un usuario con email y contraseña, devolviendo un token JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticación"
                ],
                "summary": "Iniciar sesión",
                "parameters": [
                    {
                        "description": "Datos de inicio de sesión (email y password)",
                        "name": "loginData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token",
                        "schema": {
                            "$ref": "#/definitions/controllers.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Credenciales inválidas",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Invalida la sesión actual del usuario. Requiere un Bearer Token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticación"
                ],
                "summary": "Cerrar sesión",
                "responses": {
                    "200": {
                        "description": "message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/modules": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve una lista de todos los módulos. Requiere un Bearer Token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Módulos"
                ],
                "summary": "Obtener módulos",
                "responses": {
                    "200": {
                        "description": "modules",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Module"
                            }
                        }
                    },
                    "401": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea un nuevo módulo con nombre, descripción y estado activo. Requiere un Bearer Token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Módulos"
                ],
                "summary": "Crear módulo",
                "parameters": [
                    {
                        "description": "Datos del módulo",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Module"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/modules/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve los detalles de un módulo dado su ID. Requiere un Bearer Token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Módulos"
                ],
                "summary": "Obtener módulo por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del módulo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "module",
                        "schema": {
                            "$ref": "#/definitions/models.Module"
                        }
                    },
                    "401": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Actualiza los datos de un módulo existente. Requiere un Bearer Token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Módulos"
                ],
                "summary": "Actualizar módulo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del módulo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del módulo",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Module"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina un módulo existente. Requiere un Bearer Token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Módulos"
                ],
                "summary": "Eliminar módulo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del módulo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/modules/{id}/toggle": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cambia el estado activo de un módulo existente. Requiere un Bearer Token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Módulos"
                ],
                "summary": "Cambiar estado activo del módulo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del módulo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/permissions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve una lista de permisos paginada.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permisos"
                ],
                "summary": "Obtener permisos",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Número de página (por defecto: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Tamaño de página (por defecto: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "permissions",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea un nuevo permiso con nombre, descripción, ID del módulo y estado activo. Requiere un Bearer Token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permisos"
                ],
                "summary": "Crear permiso",
                "parameters": [
                    {
                        "description": "Datos del permiso",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Permission"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "permission",
                        "schema": {
                            "$ref": "#/definitions/models.Permission"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/permissions/all": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lista todos los permisos disponibles, incluyendo los módulos a los que pertenecen",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rol_Permisos"
                ],
                "summary": "Obtener todos los permisos",
                "responses": {
                    "200": {
                        "description": "Lista de permisos",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.PermissionResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/permissions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve los detalles de un permiso dado su ID. Requiere un Bearer Token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permisos"
                ],
                "summary": "Obtener permiso por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del permiso",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "permission",
                        "schema": {
                            "$ref": "#/definitions/models.Permission"
                        }
                    },
                    "401": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Actualiza los datos de un permiso existente. Requiere un Bearer Token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permisos"
                ],
                "summary": "Actualizar permiso",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del permiso",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del permiso",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Permission"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "permission",
                        "schema": {
                            "$ref": "#/definitions/models.Permission"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/roles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve una lista paginada de roles, permitiendo filtrar por nombre y estado activo. Los resultados pueden ser paginados utilizando los parámetros ` + "`" + `page` + "`" + ` y ` + "`" + `pageSize` + "`" + `.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Obtener roles",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Número de página (por defecto 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Tamaño de página (por defecto 10)",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por nombre del rol",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por estado activo (true/false)",
                        "name": "active",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Roles obtenidos exitosamente",
                        "schema": {
                            "$ref": "#/definitions/controllers.GetRolesResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos o formato incorrecto",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseGetRoles"
                        }
                    },
                    "401": {
                        "description": "No autorizado, se requiere autenticación",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseGetRoles"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor al intentar obtener los roles",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseGetRoles"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea un nuevo rol con nombre, descripción y estado activo. Requiere un Bearer Token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Crear rol",
                "parameters": [
                    {
                        "description": "Datos del rol",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateRoleInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Rol registrado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateRoleResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos o formato incorrecto",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseRole"
                        }
                    },
                    "500": {
                        "description": "Error al registrar el Rol",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseRole"
                        }
                    }
                }
            }
        },
        "/roles/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permite actualizar los datos de un rol existente, como el nombre, descripción y estado activo. Se requiere un Bearer Token para la autenticación.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Actualizar rol",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del rol a actualizar",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Estructura que contiene los datos actualizados del rol",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateRoleInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Rol actualizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateRoleResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos o formato incorrecto",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseUpdateRole"
                        }
                    },
                    "401": {
                        "description": "No autorizado, falta el token de autenticación",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseUpdateRole"
                        }
                    },
                    "404": {
                        "description": "Rol no encontrado",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseUpdateRole"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor al intentar actualizar el rol",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseUpdateRole"
                        }
                    }
                }
            }
        },
        "/roles/{id}/state": {
            "patch": {
                "description": "Actualiza el estado de un rol existente (activo/inactivo)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Actualizar estado del rol",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del rol a actualizar",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Estado del rol a actualizar",
                        "name": "roleState",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateRoleStateInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Estado del rol actualizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateRoleStateResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos o ID incorrecto",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseUpdateRoleState"
                        }
                    },
                    "401": {
                        "description": "No se pudo obtener el ID del usuario desde el contexto",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseUpdateRoleState"
                        }
                    },
                    "500": {
                        "description": "Error interno al actualizar el estado del rol o registrar la auditoría",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseUpdateRoleState"
                        }
                    }
                }
            }
        },
        "/roles/{role_id}/permissions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lista todos los permisos asignados a un rol específico",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rol_Permisos"
                ],
                "summary": "Obtener permisos de un rol",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del rol",
                        "name": "role_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de permisos",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.PermissionResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Asocia un permiso existente a un rol específico",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rol_Permisos"
                ],
                "summary": "Asignar permiso a rol",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del rol",
                        "name": "role_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del permiso a asignar",
                        "name": "permissionData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.PermissionDataRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "role_permission",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina la asociación de un permiso específico con un rol",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rol_Permisos"
                ],
                "summary": "Eliminar permiso de rol",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del rol",
                        "name": "role_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del permiso a eliminar",
                        "name": "permissionData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.PermissionDataRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve una lista de usuarios paginada y filtrada.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "Obtener usuarios",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Número de página (por defecto: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Tamaño de página (por defecto: 10)",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por email",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filtrar por estado",
                        "name": "active",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "users",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea un nuevo usuario con nombre, email, contraseña y estado activo. Requiere un Bearer Token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "Crear usuario",
                "parameters": [
                    {
                        "description": "Datos del usuario",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.RegisterUserInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "user",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Actualiza los datos de un usuario existente. Requiere un Bearer Token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "Actualizar usuario",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del usuario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos a actualizar",
                        "name": "userData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "updatedUser",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cambia el estado de un usuario a inactivo. Requiere un Bearer Token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "Cambiar el estado del usuario",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del usuario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}/permissions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve la lista de permisos asignados a un usuario específico, dado su ID. Requiere un Bearer Token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "Obtener permisos de un usuario",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del usuario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "permissions",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}/roles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve una lista de los roles asignados a un usuario especificado por su ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Obtener roles de un usuario",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del usuario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de roles asignados",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.RoleResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "ID de usuario inválido",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseD"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseD"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Asigna un rol a un usuario especificado por su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Asignar un rol a un usuario",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del usuario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Estructura JSON con el ID del rol",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.AssignRolePayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Rol asignado correctamente",
                        "schema": {
                            "$ref": "#/definitions/controllers.UserRoleResponse"
                        }
                    },
                    "400": {
                        "description": "ID de usuario o datos inválidos",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseD"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseD"
                        }
                    }
                }
            }
        },
        "/users/{id}/roles/{role_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina un rol previamente asignado a un usuario dado su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Eliminar un rol de un usuario",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del usuario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID del rol a eliminar",
                        "name": "role_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mensaje de éxito indicando que el rol fue eliminado",
                        "schema": {
                            "$ref": "#/definitions/controllers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "ID de usuario o rol inválido",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseD"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponseD"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.AssignRolePayload": {
            "type": "object",
            "properties": {
                "role_id": {
                    "type": "integer"
                }
            }
        },
        "controllers.CreateRoleInput": {
            "type": "object",
            "required": [
                "event",
                "name"
            ],
            "properties": {
                "active": {
                    "type": "boolean",
                    "example": true
                },
                "description": {
                    "type": "string",
                    "example": "Rol con permisos de administración"
                },
                "event": {
                    "type": "string",
                    "example": "INSERT"
                },
                "name": {
                    "type": "string",
                    "example": "Administrador"
                }
            }
        },
        "controllers.CreateRoleResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Rol creado exitosamente"
                }
            }
        },
        "controllers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Credenciales inválidas"
                }
            }
        },
        "controllers.ErrorResponseAudit": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Error al realizar el registro"
                }
            }
        },
        "controllers.ErrorResponseD": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "controllers.ErrorResponseGetRoles": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Error al obtener los roles"
                }
            }
        },
        "controllers.ErrorResponseRole": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Error al crear el rol"
                }
            }
        },
        "controllers.ErrorResponseUpdateRole": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Error al actualizar el rol"
                }
            }
        },
        "controllers.ErrorResponseUpdateRoleState": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Error al actualizar el estado del rol"
                }
            }
        },
        "controllers.GetRolesResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "pageSize": {
                    "type": "integer",
                    "example": 10
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.Role"
                    }
                },
                "total": {
                    "type": "integer",
                    "example": 15
                },
                "totalPages": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "controllers.LoginData": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "securePassword123"
                }
            }
        },
        "controllers.PermissionDataRequest": {
            "type": "object",
            "properties": {
                "permission_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "controllers.PermissionResponse": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean",
                    "example": true
                },
                "description": {
                    "type": "string",
                    "example": "Permiso de Crud Usuarios"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "module_id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Gestion Usuarios"
                }
            }
        },
        "controllers.RegisterAuditInput": {
            "type": "object",
            "required": [
                "date",
                "description",
                "event",
                "origin_service",
                "user_id"
            ],
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2024-12-14T15:04:05Z"
                },
                "description": {
                    "type": "string",
                    "example": "Se creó un nuevo usuario con el email user@example.com."
                },
                "event": {
                    "type": "string",
                    "example": "INSERT"
                },
                "origin_service": {
                    "type": "string",
                    "example": "INVENTARIO"
                },
                "user_id": {
                    "type": "string",
                    "example": "123"
                }
            }
        },
        "controllers.RegisterAuditResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Auditoría registrada exitosamente"
                }
            }
        },
        "controllers.RegisterUserInput": {
            "type": "object",
            "required": [
                "active",
                "email",
                "name",
                "password"
            ],
            "properties": {
                "active": {
                    "type": "boolean",
                    "example": true
                },
                "email": {
                    "type": "string",
                    "example": "nuevousuario@gmail.com"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "password": {
                    "type": "string",
                    "example": "12345abcd"
                }
            }
        },
        "controllers.Role": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean",
                    "example": true
                },
                "description": {
                    "type": "string",
                    "example": "Gestión de usuarios"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Administrador"
                }
            }
        },
        "controllers.RoleResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "controllers.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "controllers.TokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "controllers.UpdateRoleInput": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "active": {
                    "type": "boolean",
                    "example": true
                },
                "description": {
                    "type": "string",
                    "example": "Rol para gestionar usuarios y permisos"
                },
                "name": {
                    "type": "string",
                    "example": "Administrador"
                }
            }
        },
        "controllers.UpdateRoleResponse": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean",
                    "example": true
                },
                "description": {
                    "type": "string",
                    "example": "Rol para gestionar usuarios y permisos"
                },
                "name": {
                    "type": "string",
                    "example": "Administrador"
                },
                "role_id": {
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "type": "string",
                    "example": "updated"
                }
            }
        },
        "controllers.UpdateRoleStateInput": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "controllers.UpdateRoleStateResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Estado del rol actualizado exitosamente"
                }
            }
        },
        "controllers.UserRoleResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "role_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.Module": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "permissions": {
                    "description": "Permissions []Permission ` + "`" + `gorm:\"foreignKey:ModuleID\" json:\"permissions\"` + "`" + `",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Permission"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Permission": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "module": {
                    "$ref": "#/definitions/models.Module"
                },
                "module_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.4",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "API SEGURIDAD",
	Description:      "Esta es la documentación de LA API DE SEGURIDAD hecha con Go.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
