basePath: /api
definitions:
  controllers.ErrorResponse:
    properties:
      error:
        example: Credenciales inválidas
        type: string
    type: object
  controllers.ErrorResponseAudit:
    properties:
      error:
        example: Error al realizar el registro
        type: string
    type: object
  controllers.LoginData:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: securePassword123
        type: string
    type: object
  controllers.PermissionDataRequest:
    properties:
      permission_id:
        example: 1
        type: integer
    type: object
  controllers.PermissionResponse:
    properties:
      active:
        example: true
        type: boolean
      description:
        example: Permiso de Crud Usuarios
        type: string
      id:
        example: 1
        type: integer
      module_id:
        example: 1
        type: integer
      name:
        example: Gestion Usuarios
        type: string
    type: object
  controllers.RegisterAuditInput:
    properties:
      date:
        example: "2024-12-14T15:04:05Z"
        type: string
      description:
        example: Se creó un nuevo usuario con el email user@example.com.
        type: string
      event:
        example: INSERT
        type: string
      origin_service:
        example: INVENTARIO
        type: string
      user_id:
        example: "123"
        type: string
    required:
    - date
    - description
    - event
    - origin_service
    - user_id
    type: object
  controllers.RegisterAuditResponse:
    properties:
      message:
        example: Auditoría registrada exitosamente
        type: string
    type: object
  controllers.RegisterUserInput:
    properties:
      active:
        example: true
        type: boolean
      email:
        example: nuevousuario@gmail.com
        type: string
      name:
        example: John Doe
        type: string
      password:
        example: 12345abcd
        type: string
    required:
    - active
    - email
    - name
    - password
    type: object
  controllers.TokenResponse:
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: jfpastillod@utn.edu.ec
    name: Pastillo D Joan
    url: https://www.utn.edu.ec
  description: Esta es la documentación de LA API DE SEGURIDAD hecha con Go.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: API SEGURIDAD
  version: "1.2"
paths:
  /audit:
    post:
      consumes:
      - application/json
      description: Registra un evento de auditoría en el sistema
      parameters:
      - description: Datos de auditoría a registrar
        in: body
        name: auditData
        required: true
        schema:
          $ref: '#/definitions/controllers.RegisterAuditInput'
      produces:
      - application/json
      responses:
        "200":
          description: Auditoría registrada exitosamente
          schema:
            $ref: '#/definitions/controllers.RegisterAuditResponse'
        "400":
          description: Datos inválidos o formato incorrecto
          schema:
            $ref: '#/definitions/controllers.ErrorResponseAudit'
        "500":
          description: Error al registrar la auditoría
          schema:
            $ref: '#/definitions/controllers.ErrorResponseAudit'
      summary: Registrar auditoría
      tags:
      - Auditoría
  /login:
    post:
      consumes:
      - application/json
      description: Autentica un usuario con email y contraseña, devolviendo un token
        JWT
      parameters:
      - description: Datos de inicio de sesión (email y password)
        in: body
        name: loginData
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginData'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            $ref: '#/definitions/controllers.TokenResponse'
        "400":
          description: Datos inválidos
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "401":
          description: Credenciales inválidas
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Iniciar sesión
      tags:
      - Autenticación
  /logout:
    post:
      description: Invalida la sesión actual del usuario. Requiere un Bearer Token.
      produces:
      - application/json
      responses:
        "200":
          description: message
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Cerrar sesión
      tags:
      - Autenticación
  /permissions/all:
    get:
      description: Lista todos los permisos disponibles, incluyendo los módulos a
        los que pertenecen
      produces:
      - application/json
      responses:
        "200":
          description: Lista de permisos
          schema:
            items:
              $ref: '#/definitions/controllers.PermissionResponse'
            type: array
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtener todos los permisos
      tags:
      - Rol_Permisos
  /roles:
    get:
      consumes:
      - application/json
      description: Devuelve una lista paginada de roles, permitiendo filtrar por nombre
        y estado activo.
      parameters:
      - description: Número de página (por defecto 1)
        in: query
        name: page
        type: integer
      - description: Tamaño de página (por defecto 10)
        in: query
        name: pageSize
        type: integer
      - description: Filtrar por nombre
        in: query
        name: name
        type: string
      - description: Filtrar por estado activo
        in: query
        name: active
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: roles
          schema:
            additionalProperties: true
            type: object
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Obtener roles
      tags:
      - Roles
    post:
      consumes:
      - application/json
      description: Crea un nuevo rol con nombre, descripción y estado activo. Requiere
        un Bearer Token.
      parameters:
      - description: Datos del rol
        in: body
        name: input
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: role
          schema:
            additionalProperties: true
            type: object
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Crear rol
      tags:
      - Roles
  /roles/{id}:
    put:
      consumes:
      - application/json
      description: Actualiza los datos de un rol existente identificándolo por su
        ID. Requiere un Bearer Token.
      parameters:
      - description: ID del rol
        in: path
        name: id
        required: true
        type: integer
      - description: Datos actualizados del rol
        in: body
        name: input
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: role
          schema:
            additionalProperties: true
            type: object
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Actualizar rol
      tags:
      - Roles
  /roles/{id}/state:
    patch:
      consumes:
      - application/json
      description: Cambia únicamente el estado activo de un rol identificado por su
        ID. Requiere un Bearer Token.
      parameters:
      - description: ID del rol
        in: path
        name: id
        required: true
        type: integer
      - description: Estado del rol
        in: body
        name: input
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: message
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Actualizar estado del rol
      tags:
      - Roles
  /roles/{role_id}/permissions:
    delete:
      consumes:
      - application/json
      description: Elimina la asociación de un permiso específico con un rol
      parameters:
      - description: ID del rol
        in: path
        name: role_id
        required: true
        type: integer
      - description: Datos del permiso a eliminar
        in: body
        name: permissionData
        required: true
        schema:
          $ref: '#/definitions/controllers.PermissionDataRequest'
      produces:
      - application/json
      responses:
        "200":
          description: message
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Eliminar permiso de rol
      tags:
      - Rol_Permisos
    get:
      description: Lista todos los permisos asignados a un rol específico
      parameters:
      - description: ID del rol
        in: path
        name: role_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Lista de permisos
          schema:
            items:
              $ref: '#/definitions/controllers.PermissionResponse'
            type: array
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtener permisos de un rol
      tags:
      - Rol_Permisos
    post:
      consumes:
      - application/json
      description: Asocia un permiso existente a un rol específico
      parameters:
      - description: ID del rol
        in: path
        name: role_id
        required: true
        type: integer
      - description: Datos del permiso a asignar
        in: body
        name: permissionData
        required: true
        schema:
          $ref: '#/definitions/controllers.PermissionDataRequest'
      produces:
      - application/json
      responses:
        "200":
          description: role_permission
          schema:
            additionalProperties: true
            type: object
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Asignar permiso a rol
      tags:
      - Rol_Permisos
  /users:
    get:
      description: Devuelve una lista de usuarios paginada y filtrada.
      parameters:
      - description: 'Número de página (por defecto: 1)'
        in: query
        name: page
        type: integer
      - description: 'Tamaño de página (por defecto: 10)'
        in: query
        name: pageSize
        type: integer
      - description: Filtrar por email
        in: query
        name: email
        type: string
      - description: Filtrar por estado
        in: query
        name: active
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: users
          schema:
            additionalProperties: true
            type: object
        "401":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Obtener usuarios
      tags:
      - Usuarios
    post:
      consumes:
      - application/json
      description: Crea un nuevo usuario con nombre, email, contraseña y estado activo.
        Requiere un Bearer Token.
      parameters:
      - description: Datos del usuario
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controllers.RegisterUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: user
          schema:
            additionalProperties: true
            type: object
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Crear usuario
      tags:
      - Usuarios
  /users/{id}:
    delete:
      description: Cambia el estado de un usuario a inactivo. Requiere un Bearer Token.
      parameters:
      - description: ID del usuario
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: message
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Cambiar el estado del usuario
      tags:
      - Usuarios
    put:
      consumes:
      - application/json
      description: Actualiza los datos de un usuario existente. Requiere un Bearer
        Token.
      parameters:
      - description: ID del usuario
        in: path
        name: id
        required: true
        type: string
      - description: Datos a actualizar
        in: body
        name: userData
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: updatedUser
          schema:
            additionalProperties: true
            type: object
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Actualizar usuario
      tags:
      - Usuarios
  /users/{id}/permissions:
    get:
      description: Devuelve la lista de permisos asignados a un usuario específico,
        dado su ID. Requiere un Bearer Token.
      parameters:
      - description: ID del usuario
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: permissions
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Obtener permisos de un usuario
      tags:
      - Usuarios
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
