basePath: /api
definitions:
  controllers.ErrorResponse:
    properties:
      error:
        example: Credenciales inválidas
        type: string
    type: object
  controllers.ErrorResponseAudit:
    properties:
      error:
        description: Mensaje de error
        example: Error al realizar el registro
        type: string
    type: object
  controllers.LoginData:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: securePassword123
        type: string
    type: object
  controllers.RegisterAuditInput:
    properties:
      date:
        description: Fecha en formato RFC3339
        example: "2024-12-14T15:04:05Z"
        type: string
      description:
        description: Descripción del evento
        example: Se creó un nuevo usuario con el email user@example.com.
        type: string
      event:
        description: Evento realizado
        example: INSERT
        type: string
      origin_service:
        description: Servicio de origen
        example: INVENTARIO
        type: string
      user_id:
        description: ID del usuario que realizó la acción
        example: "123"
        type: string
    required:
    - date
    - description
    - event
    - origin_service
    - user_id
    type: object
  controllers.RegisterAuditResponse:
    properties:
      message:
        description: Mensaje de éxito
        example: Auditoría registrada exitosamente
        type: string
    type: object
  controllers.TokenResponse:
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: jfpastillod@utn.edu.ec
    name: Pastillo Joan
    url: https://www.utn.edu.ec
  description: Esta es la documentación de LA API DE SEGURIDAD hecha con Go.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: API SEGURIDAD con Swagger
  version: "1.0"
paths:
  /audit:
    post:
      consumes:
      - application/json
      description: Registra un evento de auditoría en el sistema
      parameters:
      - description: Datos de auditoría a registrar
        in: body
        name: auditData
        required: true
        schema:
          $ref: '#/definitions/controllers.RegisterAuditInput'
      produces:
      - application/json
      responses:
        "200":
          description: Auditoría registrada exitosamente
          schema:
            $ref: '#/definitions/controllers.RegisterAuditResponse'
        "400":
          description: Datos inválidos o formato incorrecto
          schema:
            $ref: '#/definitions/controllers.ErrorResponseAudit'
        "500":
          description: Error al registrar la auditoría
          schema:
            $ref: '#/definitions/controllers.ErrorResponseAudit'
      summary: Registrar auditoría
      tags:
      - Auditoría
  /login:
    post:
      consumes:
      - application/json
      description: Autentica un usuario con email y contraseña, devolviendo un token
        JWT
      parameters:
      - description: Datos de inicio de sesión (email y password)
        in: body
        name: loginData
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginData'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            $ref: '#/definitions/controllers.TokenResponse'
        "400":
          description: Datos inválidos
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "401":
          description: Credenciales inválidas
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Iniciar sesión
      tags:
      - Autenticación
  /logout:
    post:
      description: Invalida la sesión actual del usuario. Requiere un Bearer Token.
      produces:
      - application/json
      responses:
        "200":
          description: message
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Cerrar sesión
      tags:
      - Autenticación
  /users:
    get:
      description: Devuelve una lista de todos los usuarios registrados. Requiere
        un Bearer Token y PIN.
      produces:
      - application/json
      responses:
        "200":
          description: users
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
        "401":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      - XAPI-PIN: []
      summary: Obtener usuarios
      tags:
      - Usuarios
    post:
      consumes:
      - application/json
      description: Crea un nuevo usuario con nombre, email, contraseña y estado activo.
        Requiere un Bearer Token y PIN.
      parameters:
      - description: Datos del usuario
        in: body
        name: input
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: user
          schema:
            additionalProperties: true
            type: object
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      - XAPI-PIN: []
      summary: Crear usuario
      tags:
      - Usuarios
  /users/{id}:
    delete:
      description: Cambia el estado de un usuario a inactivo. Requiere un Bearer Token
        y PIN.
      parameters:
      - description: ID del usuario
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: message
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      - XAPI-PIN: []
      summary: Eliminar usuario
      tags:
      - Usuarios
    put:
      consumes:
      - application/json
      description: Actualiza los datos de un usuario existente. Requiere un Bearer
        Token y PIN.
      parameters:
      - description: ID del usuario
        in: path
        name: id
        required: true
        type: string
      - description: Datos a actualizar
        in: body
        name: userData
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: updatedUser
          schema:
            additionalProperties: true
            type: object
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      - XAPI-PIN: []
      summary: Actualizar usuario
      tags:
      - Usuarios
  /users/{id}/permissions:
    get:
      description: Devuelve la lista de permisos asignados a un usuario específico,
        dado su ID. Requiere un Bearer Token.
      parameters:
      - description: ID del usuario
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: permissions
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Obtener permisos de un usuario
      tags:
      - Usuarios
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
  XAPI-PIN:
    in: header
    name: X-API-PIN
    type: apiKey
swagger: "2.0"
